name: Auto Update

on:
  push:
    branches:
      - main  # Adjust the branch name as per your repository's default branch

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This action checks out your repository's code

      - name: Fetch latest changes
        run: git fetch origin main  # Fetches the latest changes from the main branch

      - name: Merge changes
        run: git merge origin/main  # Merges the fetched changes into the current branch
